/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtomDotxmlRouteImport } from './routes/atom[.]xml'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiReactionsSlugRouteImport } from './routes/api.reactions.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtomDotxmlRoute = AtomDotxmlRouteImport.update({
  id: '/atom.xml',
  path: '/atom.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiReactionsSlugRoute = ApiReactionsSlugRouteImport.update({
  id: '/api/reactions/$slug',
  path: '/api/reactions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atom.xml': typeof AtomDotxmlRoute
  '/blog': typeof BlogRouteWithChildren
  '/rss.xml': typeof RssDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/api/reactions/$slug': typeof ApiReactionsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atom.xml': typeof AtomDotxmlRoute
  '/blog': typeof BlogRouteWithChildren
  '/rss.xml': typeof RssDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/api/reactions/$slug': typeof ApiReactionsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atom.xml': typeof AtomDotxmlRoute
  '/blog': typeof BlogRouteWithChildren
  '/rss.xml': typeof RssDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/api/reactions/$slug': typeof ApiReactionsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atom.xml'
    | '/blog'
    | '/rss.xml'
    | '/blog/$slug'
    | '/api/reactions/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atom.xml'
    | '/blog'
    | '/rss.xml'
    | '/blog/$slug'
    | '/api/reactions/$slug'
  id:
    | '__root__'
    | '/'
    | '/atom.xml'
    | '/blog'
    | '/rss.xml'
    | '/blog/$slug'
    | '/api/reactions/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtomDotxmlRoute: typeof AtomDotxmlRoute
  BlogRoute: typeof BlogRouteWithChildren
  RssDotxmlRoute: typeof RssDotxmlRoute
  ApiReactionsSlugRoute: typeof ApiReactionsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atom.xml': {
      id: '/atom.xml'
      path: '/atom.xml'
      fullPath: '/atom.xml'
      preLoaderRoute: typeof AtomDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/reactions/$slug': {
      id: '/api/reactions/$slug'
      path: '/api/reactions/$slug'
      fullPath: '/api/reactions/$slug'
      preLoaderRoute: typeof ApiReactionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtomDotxmlRoute: AtomDotxmlRoute,
  BlogRoute: BlogRouteWithChildren,
  RssDotxmlRoute: RssDotxmlRoute,
  ApiReactionsSlugRoute: ApiReactionsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
